### ISSUE TITLE
Upload of project does not upload representations

### ISSUE THREAD

**Issue by SoutheastStar** [eclipse-syson/syson#882]
Transferred a Syson file from one docker container (one computer) to another computer using docker and when I uploaded the model into the new syson site, all of the model was transferred but all the representations were lost. I am looking at how I will centrally store the model to allow others to upload it and look at the representations. As these disappear, it is hard to allow others access from a baseline doc. Is this meant to occurs?

**Comment by AxelRICHARD** [comment]
Hello, 

The semantic models and the graphical models are not stored in the same files.
If you download a project from SysON (not a model, but the entire project), you should have a.zip file containing json files, one for each semantic model and one for each diagram.
So if you only uploaded a semantic model, then it is normal that you "lost" your diagrams.

However, there is a limitation, due to [Sirius Web](https://github.com/eclipse-sirius/sirius-web), the software which SysON is based upon, implying that the upload of a zipped project will not upload the content of unsynchronized diagrams (all SysON diagrams are unsynchronized).

But, there are other solutions:
- after the upload of zipped project, you "just" have to open your diagrams (which will be empty) and use the "Add existing elements" tool available from the background of the diagrams. It will add your model elements as graphical elements in your diagrams.
- you succeed in copying the database content form a docker container to another, then you will not lose your data.
- you succeed in share your SysON instance among your end-users. Thus, they will share the same data.

Regards,

**Comment by SoutheastStar** [comment]
Cheers. I might see if I can deploy onto a server or on the cloud to save moving stuff. 

Regards.
